### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by MWRichards9** [biomed-AI/GraphSite#1]
Hi there, 

Have been trying to use the web server and am able to upload my files but not submit the form. When I press the button nothing happens as if the button is completely inert. When inspecting errors I can see the following appears:

"Failed to load resource: the server responded with a status of 400 ()" with the request URL: https://biomed.nscc-gz.cn/api/services/biomat/instance?appname=graphsite&gid=fsdzhta55ge3w6il&agent=cluster2

Is there any fix for this? Have tried clearing cache and cookies, using different browser (e.g. Chrome when Edge is my default) but no success.

**Comment by yuanqm55** [comment]
Sorry for the inconvenience. Please try our new server: http://bio-web1.nscc-gz.cn/app/graphsite
