### ISSUE TITLE
How can I prepare single representation file?

### ISSUE THREAD

**Issue by lhui2010** [biomed-AI/GraphSite#3]
Hello,

It looks alphafold2 does not output "single representation" file directly.

From the paper, it was a transformed matrix of alignment.

How can I prepare it? 

Thanks!
Hui

**Comment by yuanqm55** [comment]
Besides the predicted structures of AF2, the outputs also contain result_model_*.pkl, which is a python dictionary. You can get the single representation matrix in this dictionary via the keys of "representations" and then "single".
