### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (314,256) (384,) 

### ISSUE THREAD

**Issue by MeongBaGooBo** [biomed-AI/GraphSite#5]
Hello,

I obtained AF2 single representation using the code provided.

`import numpy as np`
`import pickle`
`with open('AF2_34714_all_rank_001_alphafold2_multimer_v3_model_3_seed_000.pickle', 'rb') as f:`
`   data = pickle.load(f)`
`np.save('AF2_single_representation.npy',data['representations']['single'])
`

I think it's format same with the example files in 'demo', but i got this error message.

Traceback (most recent call last):
  File "/app/common/bio-platform/GraphSite_new/src/script/GraphSite_predict.py", line 342, in 
    main(args.path, args.id, args.use_evo, npy = args.npy , pdb = args.pdb)
  File "/app/common/bio-platform/GraphSite_new/src/script/GraphSite_predict.py", line 301, in main
    error_code = feature_extraction(path, ID, use_evo, npy, pdb)
  File "/app/common/bio-platform/GraphSite_new/src/script/GraphSite_predict.py", line 261, in feature_extraction
    single = (single - Min_single) / (Max_single - Min_single)
ValueError: operands could not be broadcast together with shapes (314,256) (384,) 

Could you kindly let me know if there is any mistake during my procedure?

**Comment by yuanqm55** [comment]
> 

The AF2 single representation should be a matrix with a size of [L, 384], but your input seems to be a matrix with the size of [314, 256]. From your code, it seems that you use the AF multimer model, but GraphSite is only compatible with AF2 monomer.
