### ISSUE TITLE
Single representation file is of shape L x 256

### ISSUE THREAD

**Issue by stianale** [biomed-AI/GraphSite#6]
Hi,

The shape of my single representation file is L x 256, and I don't know how to linear transform (?) it into the L x 384 shape required by GraphSite.

**Comment by yuanqm55** [comment]
The single representation of AF2 monomer should be L * 384 inherently. Maybe you could provide more details about how you get this representation file?

**Comment by stianale** [comment]
I am using ColabFold and converting the L X 256 to L x 384 post hoc.

**Comment by yuanqm55** [comment]
I have used the original standalone version of AF 2.1.2 from their GitHub to develop GraphSite. I am not sure if ColabFold sticks to the original AF2.
